version: '3.5'

services:

  router1:
    build: router/.
    environment:
      - CONFIG_SERVER_NAME=config-server
      - CONFIG_SERVER_NODES=configsrv1
      - SHARD_NAME_PREFIX=shard
      - SHARD_1_NODES=shard1-a
      - SHARD_2_NODES=shard2-a
    ports:
      - 27111:27017

  configsrv1:
    build: configsrv/.
    environment:
      - CONFIG_SERVER_NAME=config-server
      - CONFIG_SERVER_NODES=configsrv1
    ports:
      - 27211:27017

  shard1-a:
    build: shard/.
    environment:
      - SHARD_NAME=shard-1
      - SHARD_NODES=shard1-a
    ports:
      - 27311:27017

  shard2-a:
    build: shard/.
    environment:
      - SHARD_NAME=shard-2
      - SHARD_NODES=shard2-a
    ports:
      - 27312:27017

