version: '3.5'

services:

  mongo-express:
    image: mongo-express:0.54.0
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=router1
    #   - ME_CONFIG_BASICAUTH_USERNAME=
    #   - ME_CONFIG_BASICAUTH_PASSWORD=
    restart: always

  router1:
    image: stutzlab/mongo-cluster-router
    environment:
      - CONFIG_REPLICA_SET=configsrv
      - CONFIG_SERVER_NODES=configsrv1,configsrv2,configsrv3
      - ADD_SHARD_REPLICA_SET_PREFIX=shard
      - ADD_SHARD_1_NODES=shard1a,shard1b,shard1c
      - ADD_SHARD_2_NODES=shard2a,shard2b,shard2c
      - ADD_SHARD_3_NODES=shard3a,shard3b
    ports:
      - 27111:27017

  router2:
    image: stutzlab/mongo-cluster-router
    environment:
      - CONFIG_REPLICA_SET=configsrv
      - CONFIG_SERVER_NODES=configsrv1,configsrv2,configsrv3
    ports:
      - 27112:27017

  configsrv1:
    image: stutzlab/mongo-cluster-configsrv
    environment:
      - CONFIG_REPLICA_SET=configsrv
      - INIT_CONFIG_NODES=configsrv1,configsrv2,configsrv3
    volumes:
      - configsrv1:/data

  configsrv2:
    image: stutzlab/mongo-cluster-configsrv
    environment:
      - CONFIG_REPLICA_SET=configsrv
    volumes:
      - configsrv2:/data

  configsrv3:
    image: stutzlab/mongo-cluster-configsrv
    environment:
      - CONFIG_REPLICA_SET=configsrv
    volumes:
      - configsrv3:/data

  shard1a:
    image: stutzlab/mongo-cluster-shard
    environment:
      - SHARD_REPLICA_SET=shard1
      - INIT_SHARD_NODES=shard1a,shard1b,shard1c
    volumes:
      - shard1a:/data

  shard1b:
    image: stutzlab/mongo-cluster-shard
    environment:
      - SHARD_REPLICA_SET=shard1
    volumes:
      - shard1b:/data

  shard1c:
    image: stutzlab/mongo-cluster-shard
    environment:
      - SHARD_REPLICA_SET=shard1
    volumes:
      - shard1c:/data

  shard2a:
    image: stutzlab/mongo-cluster-shard
    environment:
      - SHARD_REPLICA_SET=shard2
      - INIT_SHARD_NODES=shard2a,shard2b,shard2c
    volumes:
      - shard2a:/data

  shard2b:
    image: stutzlab/mongo-cluster-shard
    environment:
      - SHARD_REPLICA_SET=shard2
    volumes:
      - shard2b:/data

  shard2c:
    image: stutzlab/mongo-cluster-shard
    environment:
      - SHARD_REPLICA_SET=shard2
    volumes:
      - shard2c:/data

volumes:
  configsrv1:
  configsrv2:
  configsrv3:
  shard1a:
  shard1b:
  shard1c:
  shard2a:
  shard2b:
  shard2c:
    
